### ISSUE TITLE
Fresh installation fails to work correctly.

### ISSUE THREAD

**Issue by GlitchMasta47** [eslachance/evie.selfbot#15]
Now, read a bit before you go on a comment frenzy saying "LEARN TO CODE!" or something similar. I'm only here because I freshly cloned the selfbot into my projects folder, renamed the config.json, put in the right stuff, I mean, I did everything the README said to do. I did an install of everything, and after a while I did a sudo install to see if that would fix the issue. Of course, you may or may not know the issue. The log successfully shows my name, my correct ID, everything looks fine. I tried to run every command that was coded in the commands folder, but nothing worked. Could there be any issues with the code on GitHub itself? Reply with any question or for me to link any file and I'll put it up.

**Comment by MrJacz** [comment]
You need to do `npm install`

**Comment by GlitchMasta47** [comment]
Because you think I didn't.
Quoted from my question: 

> I did everything the README said to do. I did an install of everything...

**Comment by GlitchMasta47** [comment]
Let me just sum up everything in a simple list, because you probably didn't read it right:
- (Obviously) cloned directly from the GitHub
- Checked over the instructions in the README, and followed accordingly
- `npm install`'ed twice, another time with `sudo npm install`
- Renamed `config.json.example` to `config.json` and filled in valid information
- Ran the selfbot with `node app.js`

Just in case, what happened, if you also couldn't tell because you didn't read:
- The token was valid, as it showed my correct username and user ID in the console
- None of the commands did anything, didn't delete or edit the message at all
- There were no warnings or errors, or anything at all showing anything wrong with the code

**Comment by eslachance** [comment]
You are the 3rd person that has this issue, I'm trying to figure out what the hell it can be. Can you tell me about your system? what node version, npm version, OS version?

**Comment by eslachance** [comment]
Aaaaahahahahahaahahahahaahahahahhahaahaha
![image](https://user-images.githubusercontent.com/643344/28351640-2608dbb8-6c1f-11e7-8d5b-9cc98f0e861f.png)

I'm an idiot. I know why, it's fixed now. It's an extension thing which I fixed locally but forgot to commit to master. Apologies.
