### ISSUE TITLE
Achievement

### ISSUE THREAD

**Issue by MellyTheFireyMelly** [eslachance/evie.selfbot#21]
The MineCraft achievement command doesn't work. Does it have to do with Snekfetch? How do I fix the problem.

**Comment by kyranet** [comment]
Define 'not work', what's the issue? Did you modify it?

**Comment by MellyTheFireyMelly** [comment]
I didn't modify it. It doesn't send the image.

**Comment by MellyTheFireyMelly** [comment]
If this helps 
```js
    snekfetch.get(`https://www.minecraftskinstealer.com/achievement/a.php?i=${Random}&h=${encodeURIComponent(args.title)}&t=${encodeURIComponent(args.description)}`).then((res) => {
      msg.channel.send(msg.author, {
        files: [
          {
            attachment: res.body
          }
        ]
      }).catch(console.error);
    });

**Comment by MellyTheFireyMelly** [comment]
With the original code it just gives me an error that the message is empty.

**Comment by MrJacz** [comment]
There is a bug with D.js, iirc.

**Comment by MellyTheFireyMelly** [comment]
Is it really a bug from D.JS? Thought it was Snekfetch.

**Comment by MellyTheFireyMelly** [comment]
Alright, so the solution to this, is to run the command into the console:
`npm install hydrabolt/discord.js#11.1-dev`
