### ISSUE TITLE
Unable to create file commands/>.js on Windows

### ISSUE THREAD

**Issue by Chilace** [eslachance/evie.selfbot#5]
Ildar@Ildar-PC MINGW64 ~/Documents/GitHub
$ git clone https://github.com/eslachance/djs-selfbot.git
Cloning into 'djs-selfbot'...
remote: Counting objects: 102, done.
remote: Total 102 (delta 0), reused 0 (delta 0), pack-reused 102
Receiving objects: 100% (102/102), 35.07 KiB | 0 bytes/s, done.
Resolving deltas: 100% (38/38), done.
error: unable to create file commands/>.js: Invalid argument
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

Ildar@Ildar-PC MINGW64 ~/Documents/GitHub
$ git status
fatal: Not a git repository (or any of the parent directories): .git

Ildar@Ildar-PC MINGW64 ~/Documents/GitHub
$

**Comment by eslachance** [comment]
Unfortunately nothing I can do about this. I don't host it on Windows, and I have no way to really "fix" that without modifying the behaviour that I'm used to.
